/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './treeview-demo';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './treeview';
import * as import9 from './treeview.ngfactory';
export class Wrapper_TreeviewDemo {
  /*private*/ _eventHandler:Function;
  context:import0.TreeviewDemo;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.TreeviewDemo();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_TreeviewDemo_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_TreeviewDemo_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.TreeviewDemo>;
  _TreeviewDemo_0_3:Wrapper_TreeviewDemo;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TreeviewDemo_Host0,renderType_TreeviewDemo_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'treeview-demo',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_TreeviewDemo0(this.viewUtils,this,0,this._el_0);
    this._TreeviewDemo_0_3 = new Wrapper_TreeviewDemo();
    this.compView_0.create(this._TreeviewDemo_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._TreeviewDemo_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TreeviewDemo) && (0 === requestNodeIndex))) { return this._TreeviewDemo_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TreeviewDemo_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const TreeviewDemoNgFactory:import7.ComponentFactory<import0.TreeviewDemo> = new import7.ComponentFactory<import0.TreeviewDemo>('treeview-demo',View_TreeviewDemo_Host0,import0.TreeviewDemo);
const styles_TreeviewDemo:any[] = ([] as any[]);
var renderType_TreeviewDemo:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_TreeviewDemo,{});
export class View_TreeviewDemo0 extends import1.AppView<import0.TreeviewDemo> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  compView_3:import1.AppView<import8.Treeview>;
  _Treeview_3_3:import9.Wrapper_Treeview;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TreeviewDemo0,renderType_TreeviewDemo,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Recursive TreeView',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n             ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'treeview',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_3 = new import9.View_Treeview0(this.viewUtils,this,3,this._el_3);
    this._Treeview_3_3 = new import9.Wrapper_Treeview();
    this.compView_3.create(this._Treeview_3_3.context);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import8.Treeview) && (3 === requestNodeIndex))) { return this._Treeview_3_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3_0_0:any = this.context.directories;
    this._Treeview_3_3.check_directories(currVal_3_0_0,throwOnChange,false);
    this._Treeview_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    this.compView_3.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_3.destroy();
  }
}